name: Go Checks
on:
  - push

env:
  DEBIAN_FRONTEND: noninteractive
  GOPRIVATE: '*.infrastructureiscode.ca,*.iscode.ca'

jobs:
  check:
    name: Run Go lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs for Actions
        run: |
          apt-get update
          apt-get -y --no-install-recommends install curl gnupg git ca-certificates
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.5'
      - name: Allow access to iscode.ca Go packages
        run: |
          echo "machine git.iscode.ca login ci password ${{ secrets.GITEA_TOKEN }}" >$HOME/.netrc
      - name: Install and run golangci
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.2
          golangci-lint run --timeout 2m0s
      - name: Run tests
        run: |
          go test ./...
      - name: Install and run vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
